# 间隔秒数，最少60秒
interval: 60

# 源文件夹
source_folders: 
  - D:\work\cesiumlab\ori
  - D:\work\Incre-Backup
  - D:\work\py_desktop
  - D:\work\CIMToolBox
  - D:\work\BTUtils
  - D:\work\CIMelperModelTools
  - D:\work\cimelper
  - D:\work\electron-fragment
  
# 备份根目录
backup_root:  C:\BACKUP
 
# 排除项
excludes:
  - '*/.git/*'
  - '*/.vs/*'
  - '*/.idea/*'
  - '*/__pycache__/*'
  - '*/Debug/*'
  - '*/Release/*'
  - '*/ori/3rd/*'
  - '*/ori/3rdsrc/*'
  - '*.zip'
  - '*.rar'
  - '*/pid'
  - '*/CIMToolBox/cpp_for_py/*'
  - '*/CIMToolBox/libs/*'
  - '*/x64/*'
  - '*/bin/*'
  - '*/obj/*'
  - '*/packages/*'
  - '*/node_modules/*'
